### ISSUE TITLE
consumers.pyの記述(採点周り以外)

### ISSUE THREAD

**Issue by MATCHAo2** [INIAD-FES-2022/quiz-project#1]
管理者画面から指令のWebSocketを受信したら、すべてのクライアントにその指令を送るという機能です

Consumerでやること
- def connect(self)
  - ここでハンドシェイク時の挙動を決めます
    - self.room_group_name = "テキトーな名前" として、groupの名前を一意にして…
    - self.channel_name = self.scope["url_route"]["kwargs"]["userid"] として、チャンネルの名前をネームカードのUUIDにして…
      - useridが渡されていない場合は、新しくUUIDを作ります
    - self.channel_layer.group_add() で上の２つを用いてchannelをgroupに追加します
  - 上の処理が終わったら、実際に接続します
    - self.accept()

- def receive(self, text_data)
  - json文字列が届いたときの挙動を決めます
  - これは後でSlackにも投げるんですが、jsonの中に"isStaff"みたいな項目を追加して、管理者画面からの操作とクライアントからの操作とで分けたほうがいいかもしれません
  - 管理者画面からのメッセージを受信したときの動作
    - self.channel_layer.group_send()を用いて、上で決めた"テキトーな名前"のgroupに指令を送ってください
  - クライアント(クイズの参加者画面)からのメッセージを受信したときの動作
    - 落合くんに任せる感じになりそう(？？？)

冗長な文ですみませんが、こんな流れで実装する感じになるかな〜と思います
対応が遅くなりましてすみませんでした。よろしくお願いします。🙇‍♂️

**Comment by Takuho3650** [comment]
issueの割り振りに加えて、詳細な実装方法をご教示下さりありがとうございます。
求められている作業、その手順が明確化されていたので非常に助かりました。
Consumer.py及び関連ファイルの追加、修正をしましたので、お手すきの際に確認をお願いします。
